/**
 * `@theme/Landing` — the homepage of a vsor site.
 *
 * The point of this component is that a homepage should not need writing. The
 * name and tagline come from `docusaurus.config.ts`; the cards come from the
 * corpus's own top-level folders; the only sentences the framework supplies
 * describe the framework's own contract (one source, two surfaces) and can be
 * replaced or removed by prop. Nothing on this page is inherited copy, an
 * inherited link, or an inherited image.
 *
 * The scaffold's `site/src/pages/index.tsx` is therefore three lines. An owner
 * who wants more control passes props; an owner who wants the whole thing writes
 * `site/src/theme/Landing/index.tsx`, which Docusaurus resolves ahead of any
 * installed theme — the destination `docusaurus swizzle --eject` would choose,
 * reached the way this framework reaches everything: a native seam, no new verb.
 *
 * Design lineage: the structure — full-bleed hero, hairline grids, mono kickers,
 * sharp corners — is upstream's (ag2 apps/learn-app at d764f334), reworked. The
 * reasons for each divergence are recorded beside the divergence.
 */
import Layout from "@theme/Layout";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import React from "react";
import Hero from "./Hero";
import SectionCards from "./SectionCards";
import Surfaces from "./Surfaces";
import { useCorpus } from "./useCorpus";
import type { LandingProps, LandingSurface } from "./types";

/**
 * The two surfaces of the system of record, in the tense each has earned.
 * Exported so an owner can keep one and replace the other.
 */
export const DEFAULT_SURFACES: LandingSurface[] = [
  {
    title: "This website",
    description:
      "Every document in the knowledge folder is published here, with a sidebar generated from the folder tree and a search index that ships inside the site — there is nothing for a reader's browser to call out to.",
    status: "live",
    icon: "globe",
  },
  {
    title: "An MCP server",
    description:
      "The same documents, read by AI assistants over MCP: answers cited back to the source, and an honest abstention when the corpus does not cover the question. It does not serve yet — the verb that runs it arrives in a later release.",
    status: "later",
    icon: "server",
  },
];

const DEFAULT_CTA_LABEL = "Read the knowledge base";

export default function Landing(props: LandingProps): React.ReactElement {
  const { siteConfig } = useDocusaurusContext();
  const corpus = useCorpus();

  const title = props.title ?? siteConfig.title;
  const tagline = props.tagline ?? siteConfig.tagline ?? undefined;

  // The default action points at the corpus's own main document rather than at
  // the docs route: with an autogenerated sidebar and no index page, "/docs" is
  // not a route at all, and Docusaurus's broken-link check would fail the build.
  const derivedCta = corpus.mainDocPath
    ? { label: DEFAULT_CTA_LABEL, href: corpus.mainDocPath }
    : undefined;
  const cta = props.cta === false ? undefined : (props.cta ?? derivedCta);

  const sections =
    props.sections === false ? [] : (props.sections ?? corpus.sections);
  const surfaces =
    props.surfaces === false ? [] : (props.surfaces ?? DEFAULT_SURFACES);

  // Derived, never invented: the mono note beside the grid heading states what
  // the grid is a summary of.
  const note =
    props.sections === undefined && corpus.documentCount > 0
      ? `${corpus.documentCount} document${corpus.documentCount === 1 ? "" : "s"}${
          corpus.basePath ? `, published at ${corpus.basePath}` : ""
        }`
      : undefined;

  return (
    <Layout description={tagline}>
      {/* Docusaurus's Layout wraps children in a div, and doc pages supply their
          own <main>. The homepage has none, so it supplies one — otherwise the
          skip-to-content link lands on a container with no landmark role. */}
      <main>
        <Hero
          title={title}
          tagline={tagline}
          eyebrow={props.eyebrow}
          cta={cta}
          secondaryCta={props.secondaryCta}
          corpus={corpus}
        />
        <SectionCards
          sections={sections}
          kicker={props.sectionsKicker ?? "Contents"}
          heading={props.sectionsHeading ?? "What this covers"}
          note={note}
        />
        <Surfaces
          surfaces={surfaces}
          kicker={props.surfacesKicker ?? "Surfaces"}
          heading={props.surfacesHeading ?? "One source, two surfaces"}
        />
        {props.children}
      </main>
    </Layout>
  );
}

export type {
  LandingProps,
  LandingSection,
  LandingSurface,
  LandingLink,
} from "./types";
