"""Unit contract for `vsor/site_runtime.py` — written red-first from
specs/vsor/build/spec.md ("The runtime shell — materialization and staleness",
"Preconditions, stated not assumed").

Public surface these tests define:

- `probe_node_version() -> str | None` — the measured node version, no leading `v`
  (e.g. "24.4.1"); None when node is not on PATH. Verbs call it as a module attribute
  (`site_runtime.probe_node_version()`) so tests can monkeypatch the probe.
- `check_node(version: str | None) -> None` — raises `CommandError("missing-runtime", …)`
  (exit 3) when node is absent OR too old (< 20); the remedy names what was measured
  and where to install (nodejs.org).
- `ensure_runtime(project_root: Path) -> Path` — materializes `.vsor/site-runtime/` and
  returns it; also a module attribute, the monkeypatch seam for the command tests.
- `write_stamp(runtime_dir, *, vsor_version, package_json, lock) -> None` — writes
  `.materialized.json` = {vsor, package_json_sha256, lock_sha256}, only ever AFTER a
  successful `npm ci` (an interrupted install never writes it).
- `stamp_is_current(runtime_dir, *, vsor_version, package_json, lock) -> bool` — reuse
  the shell iff the stamp matches the freshly generated bytes; absence, mismatch, or a
  corrupt stamp all mean wipe-and-rematerialize, never a crash.
"""

import hashlib
import json
from pathlib import Path

import pytest
from vsor import site_runtime
from vsor.errors import CommandError

VSOR_VERSION = "0.1.0"
PACKAGE_JSON = b'{"name": "site-runtime-shell", "private": true}\n'
LOCKFILE = b'{"lockfileVersion": 3}\n'


def current(
    runtime_dir: Path,
    *,
    vsor_version: str = VSOR_VERSION,
    package_json: bytes = PACKAGE_JSON,
    lock: bytes = LOCKFILE,
) -> bool:
    result = site_runtime.stamp_is_current(
        runtime_dir, vsor_version=vsor_version, package_json=package_json, lock=lock
    )
    assert isinstance(result, bool)
    return result


def test_module_seams_exist() -> None:
    """The command layer reaches these through the module object — the monkeypatch seam."""
    assert callable(site_runtime.probe_node_version)
    assert callable(site_runtime.ensure_runtime)


# ------------------------------------------------------------------ the .materialized.json stamp


def test_absent_stamp_means_rematerialize(tmp_path: Path) -> None:
    assert current(tmp_path) is False


def test_stamp_round_trip_means_reuse(tmp_path: Path) -> None:
    site_runtime.write_stamp(tmp_path, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE)
    assert current(tmp_path) is True


def test_stamp_file_shape_is_the_spec_shape(tmp_path: Path) -> None:
    """`.materialized.json` carries exactly {vsor, package_json_sha256, lock_sha256}."""
    site_runtime.write_stamp(tmp_path, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE)
    data = json.loads((tmp_path / ".materialized.json").read_text(encoding="utf-8"))
    assert data == {
        "vsor": VSOR_VERSION,
        "package_json_sha256": hashlib.sha256(PACKAGE_JSON).hexdigest(),
        "lock_sha256": hashlib.sha256(LOCKFILE).hexdigest(),
    }


def test_changed_package_json_is_stale(tmp_path: Path) -> None:
    site_runtime.write_stamp(tmp_path, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE)
    assert current(tmp_path, package_json=PACKAGE_JSON + b" ") is False


def test_changed_lockfile_is_stale(tmp_path: Path) -> None:
    site_runtime.write_stamp(tmp_path, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE)
    assert current(tmp_path, lock=LOCKFILE + b" ") is False


def test_upgraded_vsor_is_stale(tmp_path: Path) -> None:
    """This is what keeps an upgraded vsor from silently building with old JS."""
    site_runtime.write_stamp(tmp_path, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE)
    assert current(tmp_path, vsor_version="0.2.0") is False


def test_partial_install_without_stamp_is_stale(tmp_path: Path) -> None:
    """An interrupted `npm ci` leaves node_modules debris but never a stamp —
    debris alone must not count as materialized."""
    (tmp_path / "node_modules" / ".package-lock.json").parent.mkdir(parents=True)
    (tmp_path / "node_modules" / ".package-lock.json").write_bytes(b"{}")
    (tmp_path / "package.json").write_bytes(PACKAGE_JSON)
    assert current(tmp_path) is False


def test_corrupt_stamp_is_stale_never_a_crash(tmp_path: Path) -> None:
    (tmp_path / ".materialized.json").write_text("not json at all {", encoding="utf-8")
    assert current(tmp_path) is False


# ------------------------------------------------------------------ the node precondition


def test_check_node_absent_is_missing_runtime() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node(None)
    assert exc.value.slug == "missing-runtime"
    assert exc.value.exit_code == 3
    message = str(exc.value)
    assert "node" in message.lower()
    assert "nodejs.org" in message  # the remedy names the install


def test_check_node_too_old_names_the_measured_version() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node("18.19.0")
    assert exc.value.slug == "missing-runtime"
    assert exc.value.exit_code == 3
    message = str(exc.value)
    assert "18.19" in message  # what was measured
    assert "20" in message  # what is needed


def test_check_node_19_is_still_too_old() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node("19.9.9")
    assert exc.value.slug == "missing-runtime"


@pytest.mark.parametrize("version", ["20.0.0", "22.12.0", "24.4.1"])
def test_check_node_20_plus_passes(version: str) -> None:
    site_runtime.check_node(version)  # must not raise
