"""Unit contract for `vsor/site_runtime.py` — written red-first from
specs/vsor/build/spec.md ("The runtime shell — materialization and staleness",
"Preconditions, stated not assumed").

Public surface these tests define:

- `probe_node_version() -> str | None` — the measured node version, no leading `v`
  (e.g. "24.4.1"); None when node is not on PATH. Verbs call it as a module attribute
  (`site_runtime.probe_node_version()`) so tests can monkeypatch the probe.
- `check_node(version: str | None) -> None` — raises `CommandError("missing-runtime", …)`
  (exit 3) when node is absent OR too old (< 20); the remedy names what was measured
  and where to install (nodejs.org).
- `ensure_runtime(project_root: Path) -> Path` — materializes `.vsor/site-runtime/` and
  returns it; also a module attribute, the monkeypatch seam for the command tests.
- `write_stamp(runtime_dir, *, vsor_version, package_json, lock, app) -> None` — writes
  `.materialized.json` = {vsor, package_json_sha256, lock_sha256, app_sha256}, only ever
  AFTER a successful `npm ci` (an interrupted install never writes it).
- `stamp_is_current(runtime_dir, *, vsor_version, package_json, lock, app) -> bool` —
  reuse the shell iff the stamp matches the freshly generated bytes; absence, mismatch,
  or a corrupt stamp all mean wipe-and-rematerialize, never a crash.
- `library_tarballs(package_json) -> tuple[str, ...]` — the `file:./…tgz` dependencies
  the shell manifest names, which is what materialization copies out of the wheel.
- `runtime_env()` — the environment the verbs run Docusaurus under: the app's corpus and
  site seams pointed at the copies inside the shell.

`app_sha256` joined the stamp on 2026-08-14, when the shell became the forked app: the
app is UNPACKED over the shell rather than installed into node_modules, so a changed fork
with an unchanged dependency set leaves package.json and package-lock.json byte-identical
and the old shell would have been reused as current. The library tarballs need no hash
here — npm records their sha512 in the lockfile, so changing one moves `lock_sha256`.
"""

import hashlib
import json
from pathlib import Path

import pytest
from vsor import site_runtime
from vsor.errors import CommandError

VSOR_VERSION = "0.1.0"
PACKAGE_JSON = b'{"name": "site-runtime-shell", "private": true}\n'
LOCKFILE = b'{"lockfileVersion": 3}\n'
APP = b"not really a tarball, but bytes are bytes\n"


def current(
    runtime_dir: Path,
    *,
    vsor_version: str = VSOR_VERSION,
    package_json: bytes = PACKAGE_JSON,
    lock: bytes = LOCKFILE,
    app: bytes = APP,
) -> bool:
    result = site_runtime.stamp_is_current(
        runtime_dir, vsor_version=vsor_version, package_json=package_json, lock=lock, app=app
    )
    assert isinstance(result, bool)
    return result


def write(runtime_dir: Path) -> None:
    site_runtime.write_stamp(
        runtime_dir, vsor_version=VSOR_VERSION, package_json=PACKAGE_JSON, lock=LOCKFILE, app=APP
    )


def test_module_seams_exist() -> None:
    """The command layer reaches these through the module object — the monkeypatch seam."""
    assert callable(site_runtime.probe_node_version)
    assert callable(site_runtime.ensure_runtime)


# ------------------------------------------------------------------ the .materialized.json stamp


def test_absent_stamp_means_rematerialize(tmp_path: Path) -> None:
    assert current(tmp_path) is False


def test_stamp_round_trip_means_reuse(tmp_path: Path) -> None:
    write(tmp_path)
    assert current(tmp_path) is True


def test_stamp_file_shape_is_the_spec_shape(tmp_path: Path) -> None:
    """`.materialized.json` carries exactly
    {vsor, package_json_sha256, lock_sha256, app_sha256}."""
    write(tmp_path)
    data = json.loads((tmp_path / ".materialized.json").read_text(encoding="utf-8"))
    assert data == {
        "vsor": VSOR_VERSION,
        "package_json_sha256": hashlib.sha256(PACKAGE_JSON).hexdigest(),
        "lock_sha256": hashlib.sha256(LOCKFILE).hexdigest(),
        "app_sha256": hashlib.sha256(APP).hexdigest(),
    }


def test_changed_package_json_is_stale(tmp_path: Path) -> None:
    write(tmp_path)
    assert current(tmp_path, package_json=PACKAGE_JSON + b" ") is False


def test_changed_lockfile_is_stale(tmp_path: Path) -> None:
    write(tmp_path)
    assert current(tmp_path, lock=LOCKFILE + b" ") is False


def test_changed_app_tarball_is_stale(tmp_path: Path) -> None:
    """The shell IS the app, unpacked — so a rebuilt fork with an unchanged dependency
    set must still invalidate the shell. Nothing else in the stamp would move."""
    write(tmp_path)
    assert current(tmp_path, app=APP + b" ") is False


def test_upgraded_vsor_is_stale(tmp_path: Path) -> None:
    """This is what keeps an upgraded vsor from silently building with old JS."""
    write(tmp_path)
    assert current(tmp_path, vsor_version="0.2.0") is False


def test_partial_install_without_stamp_is_stale(tmp_path: Path) -> None:
    """An interrupted `npm ci` leaves node_modules debris but never a stamp —
    debris alone must not count as materialized."""
    (tmp_path / "node_modules" / ".package-lock.json").parent.mkdir(parents=True)
    (tmp_path / "node_modules" / ".package-lock.json").write_bytes(b"{}")
    (tmp_path / "package.json").write_bytes(PACKAGE_JSON)
    assert current(tmp_path) is False


def test_corrupt_stamp_is_stale_never_a_crash(tmp_path: Path) -> None:
    (tmp_path / ".materialized.json").write_text("not json at all {", encoding="utf-8")
    assert current(tmp_path) is False


# ------------------------------------------------------------------ the node precondition


def test_check_node_absent_is_missing_runtime() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node(None)
    assert exc.value.slug == "missing-runtime"
    assert exc.value.exit_code == 3
    message = str(exc.value)
    assert "node" in message.lower()
    assert "nodejs.org" in message  # the remedy names the install


def test_check_node_too_old_names_the_measured_version() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node("18.19.0")
    assert exc.value.slug == "missing-runtime"
    assert exc.value.exit_code == 3
    message = str(exc.value)
    assert "18.19" in message  # what was measured
    assert "20" in message  # what is needed


def test_check_node_19_is_still_too_old() -> None:
    with pytest.raises(CommandError) as exc:
        site_runtime.check_node("19.9.9")
    assert exc.value.slug == "missing-runtime"


@pytest.mark.parametrize("version", ["20.0.0", "22.12.0", "24.4.1"])
def test_check_node_20_plus_passes(version: str) -> None:
    site_runtime.check_node(version)  # must not raise


# ------------------------------------------------------------------ the shell's version mirror


REPO = Path(__file__).resolve().parents[3]
SHELL_TEMPLATE = REPO / "packages/vsor/src/vsor/templates/site_runtime/package.json"
APP_MANIFEST = REPO / "packages/sor-site/app/package.json"
WORKSPACE_LOCK = REPO / "packages/sor-site/package-lock.json"
SHELL_LOCK = REPO / "packages/vsor/src/vsor/templates/site_runtime/package-lock.json"

# devDependencies of the fork that a BUILD needs, so the shell must install them as
# ordinary dependencies: the faster toolchain the config's `future.faster` block turns
# on, and the postcss/tailwind chain postcss.config.js loads. Everything else in the
# fork's devDependencies is type-only (@types/*, typescript, @docusaurus/{types,
# tsconfig, module-type-aliases}) — nothing in a build reads them, and the shell is
# scratch rather than an editing surface.
BUILD_DEV_DEPS = frozenset(
    {
        "@docusaurus/faster",
        "@tailwindcss/postcss",
        "autoprefixer",
        "postcss",
        "tailwindcss",
        "tailwindcss-animate",
    }
)


def _resolved_versions() -> dict[str, str]:
    """name -> version as packages/sor-site/package-lock.json resolved it for the app.

    The app's OWN nested tree wins over the hoisted one: the workspace hoists whatever
    the first requester needed (remark-directive 3.0.1, for the not-yet-deleted theme
    package) and nests the app's real version under `app/node_modules/`. A shell that
    mirrored the hoisted row would ship the fork a version it never ran."""
    lock = json.loads(WORKSPACE_LOCK.read_text())
    hoisted: dict[str, str] = {}
    nested: dict[str, str] = {}
    for path, entry in lock["packages"].items():
        version = entry.get("version")
        if version is None:
            continue
        if path.startswith("node_modules/") and path.count("node_modules/") == 1:
            hoisted[path[len("node_modules/") :]] = version
        elif path.startswith("app/node_modules/") and path.count("node_modules/") == 1:
            nested[path[len("app/node_modules/") :]] = version
    return hoisted | nested


def test_shell_pins_mirror_the_proven_lockfile() -> None:
    """The shell template's exact pins equal the versions the workspace resolved.

    The shell (templates/site_runtime/package.json) is what every USER's site is
    built from; packages/sor-site/package-lock.json is what the fork itself is
    developed and exercised against. The two were mirrored by hand and nothing
    compared them — one `npm install` that bumped the workspace would have diverged
    every user's build from the only set ever exercised, silently.
    """
    shell = json.loads(SHELL_TEMPLATE.read_text())
    resolved = _resolved_versions()

    mismatches: list[str] = []
    for name, pin in sorted(shell["dependencies"].items()):
        if pin.startswith("file:"):
            continue  # the tarballs `make wheel` stages — no lockfile row exists
        actual = resolved.get(name)
        if actual != pin:
            mismatches.append(f"{name}: shell pins {pin}, sor-site lockfile resolves {actual}")
    assert not mismatches, (
        "the site-runtime shell no longer mirrors packages/sor-site/package-lock.json — a user's "
        "build would run versions the fork was never exercised with. Re-pin the shell (or re-run "
        "`npm install` in packages/sor-site and re-run `make surface`) in the same change:\n"
        + "\n".join(mismatches)
    )


def test_shell_carries_every_dependency_the_fork_declares() -> None:
    """The shell manifest REPLACES the app's own when the app is unpacked, so anything
    the fork gains and the shell does not is a module that resolves in the workspace and
    is missing from every user's install — a build that is green here and red there."""
    shell = json.loads(SHELL_TEMPLATE.read_text())["dependencies"]
    app = json.loads(APP_MANIFEST.read_text())
    wanted = set(app["dependencies"]) | (set(app["devDependencies"]) & BUILD_DEV_DEPS)
    missing = sorted(wanted - set(shell))
    assert not missing, (
        "packages/sor-site/app/package.json declares dependencies the site-runtime shell does "
        "not install — add them (pinned to what the workspace lockfile resolved; workspace "
        "@vsor/* packages become `file:./<name>.tgz` and a line in `make wheel`'s `packed`):\n"
        + "\n".join(missing)
    )


def test_workspace_libraries_ship_as_relative_tarballs() -> None:
    """Every `@vsor/*` the fork imports ships as a file: tarball, because the version it
    declares (0.1.0) exists on no registry. Relative, never absolute: the shell must
    survive `uv cache prune`."""
    shell = json.loads(SHELL_TEMPLATE.read_text())["dependencies"]
    app = json.loads(APP_MANIFEST.read_text())["dependencies"]
    for name in sorted(n for n in app if n.startswith("@vsor/")):
        assert shell.get(name) == f"file:./{name.removeprefix('@vsor/')}.tgz", (
            f"{name} must ship as a relative tarball in the shell manifest"
        )
    assert site_runtime.library_tarballs(SHELL_TEMPLATE.read_bytes()), (
        "library_tarballs found no file: dependencies — the shell would install nothing local"
    )


def test_runtime_env_points_the_app_at_the_copies_inside_the_shell() -> None:
    """The fork defaults to sibling `../knowledge` and `../site` (its own workspace
    layout); materialization puts both INSIDE the shell, so the verbs say so."""
    env = site_runtime.runtime_env({"PATH": "/usr/bin"})
    assert env["VSOR_KNOWLEDGE_DIR"] == "./knowledge"
    assert env["VSOR_SITE_DIR"] == "./site"
    assert env["PATH"] == "/usr/bin"  # the ambient environment is carried, not replaced


def test_shell_resolves_the_same_browser_targets_as_the_fork() -> None:
    """`browserslist` is not a dependency, but it decides how the CSS is COMPILED — and
    the shell manifest REPLACES the app's, so an absent field is not "inherit", it is
    "fall back to browserslist's own defaults".

    Those defaults include and_qq, and_uc and kaios, none of which support cascade
    layers. postcss-preset-env — which Docusaurus installs with an empty options object —
    then rewrites every `@layer` into `:not(#\\#)` specificity chains, Tailwind's preflight
    (`* { margin:0; padding:0; border:0 }`) arrives at (2,0,0), and every single-class
    CSS-module rule in the shell loses its box. That shipped in 0.1.2 and the browser tier
    never saw it: the e2e fixture copies the APP directory, so it kept the app's
    browserslist and compiled correctly while the artifact did not.

    found live 2026-08-15 on the deployed demo. The targets must match, or the tier is
    certifying a different compiler than the one users run.
    """
    shell = json.loads(SHELL_TEMPLATE.read_text())
    app = json.loads(APP_MANIFEST.read_text())
    assert shell.get("browserslist") == app.get("browserslist"), (
        "the site-runtime shell and packages/sor-site/app/package.json must declare the "
        "same `browserslist`; they compile the same CSS and a divergence changes which "
        "PostCSS polyfills run in a real `vsor build` but not in the e2e fixture"
    )


def test_the_shipped_lockfile_is_the_shipped_manifest_resolved() -> None:
    """The lockfile beside the shell manifest is the tree every user installs, and since
    2026-08-15 it is committed rather than re-resolved on each `make wheel`.

    That makes it reviewable — the repository's supply-chain rule calls the lockfile the
    dependency review surface, and this was the one dependency set nobody could read — but
    it also makes it possible for the two files to drift apart. A manifest naming a package
    the lock does not resolve fails at `npm ci` in a user's project, long after anyone is
    watching. This row is the coupling: edit the manifest, run `make relock`, commit both.
    """
    shell = json.loads(SHELL_TEMPLATE.read_text())
    lock = json.loads(SHELL_LOCK.read_text())

    root = lock["packages"][""]
    assert root.get("name") == shell["name"], (
        "the lockfile was resolved from a different manifest than the one beside it"
    )
    assert root.get("dependencies") == shell["dependencies"], (
        "templates/site_runtime/package.json and its package-lock.json declare different "
        "dependencies — run `make relock` and commit both files together"
    )

    for name, spec in sorted(shell["dependencies"].items()):
        entry = lock["packages"].get(f"node_modules/{name}")
        assert entry is not None, (
            f"{name} is declared in the shell manifest but resolves to nothing in the "
            "lockfile — run `make relock`"
        )
        if spec.startswith("file:"):
            # A workspace library. npm records where it came from and the hash of the
            # tarball `make wheel` packs; the pin itself is the path, not a version.
            tarball = spec.removeprefix("file:").removeprefix("./")
            assert entry.get("resolved") == f"file:{tarball}", (
                f"{name} should resolve to the relative tarball {spec} — an absolute or "
                "registry resolution would not survive `uv cache prune` on a user's machine"
            )
        else:
            assert entry.get("version") == spec, (
                f"the shell manifest pins {name} {spec} but the lockfile resolves "
                f"{entry.get('version')} — run `make relock`"
            )
