// This site is yours. Every value here is a live seam — edit it and the built
// site changes. The knowledge itself lives in ../knowledge; this file only
// decides how it is presented.
import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";

const config: Config = {
  title: "__VSOR_NAME__",
  url: "http://localhost:3000", // set to your real domain when you deploy
  baseUrl: "/",
  i18n: { defaultLocale: "en", locales: ["en"] },

  presets: [
    [
      "classic",
      {
        docs: {
          path: "../knowledge",
          routeBasePath: "docs",
          // no sidebarPath: the sidebar is autogenerated from the folder tree
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: { title: "__VSOR_NAME__" },
    footer: { copyright: `© __VSOR_YEAR__ __VSOR_NAME__` },
  } satisfies Preset.ThemeConfig,
};

export default config;
