// The sidebar is generated from the knowledge/ folder tree, so adding a document
// is all it takes to make it appear. Order comes from `sidebar_position:` in a
// document's frontmatter, then filename.
//
// It is named `tutorialSidebar` on purpose: that is the name create-docusaurus
// gives every site, so documents copied in from an existing Docusaurus project —
// which carry `displayed_sidebar: tutorialSidebar` in their frontmatter — build
// here without being edited first. (found live: with the sidebar left unnamed,
// Docusaurus calls it `defaultSidebar` and one such document fails the build.)
//
// To hand-order sections instead, replace the autogenerated entry with an
// explicit list — the Docusaurus sidebar format, documented and unchanged here.
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
