/**
 * Search utilities over the LOCAL search index generated by
 * @easyops-cn/docusaurus-search-local (`search-index.json` — the site must
 * configure that theme with `hashed: false` so the filename is stable).
 *
 * Copied from ag2 apps/learn-app src/lib/search-utils.ts at d764f334.
 * Changes on copy (surface spec: "the theme introduces no external
 * requests"):
 *   - upstream loaded Lunr.js from a third-party CDN at runtime — a
 *     theme-introduced external request that B8's network interception
 *     would rightly fail. Lunr is now a bundled npm dependency; the CDN
 *     loader is gone.
 *   - the base-path detection's known-routes list dropped the product
 *     routes ('auth', 'api', 'code'); the framework site has none of them.
 * Everything else — the additive scoring fallback, the Levenshtein fuzzy
 * matcher, the lunr query building — is upstream code kept as-is.
 */

import lunr from "lunr";

export interface SearchResult {
  title: string;
  url: string;
  text?: string;
  type?: string;
  score?: number;
}

// ============================================================================
// CONSTANTS — scoring weights and thresholds
// ============================================================================

/**
 * Scoring weights for different match types in fallback search.
 *
 * NOTE: These scores are ADDITIVE, not exclusive. A single term match
 * can trigger multiple scoring tiers; better matches accumulate higher
 * scores naturally.
 */
export const SCORE_WEIGHTS = {
  EXACT_TITLE: 100, // Title exactly equals the search term
  TITLE_STARTS_WITH: 50, // Title starts with the search term
  SUBSTRING_IN_TITLE: 25, // Term appears anywhere in title
  EXACT_WORD_IN_TITLE: 20, // Term matches a complete word in title
  PARTIAL_WORD_IN_TITLE: 15, // Term matches start of a word in title
  FUZZY_WORD_IN_TITLE: 10, // Fuzzy match (Levenshtein) on title words
  IN_BREADCRUMBS: 5, // Term appears in breadcrumbs
  PARTIAL_IN_BREADCRUMBS: 2, // Partial match in breadcrumbs
} as const;

const LEVENSHTEIN_BASE_SCORE = 10;
const LEVENSHTEIN_DISTANCE_PENALTY = 2;
const LEVENSHTEIN_MIN_SCORE = 5;

const FUZZY_MAX_EDITS_SHORT_TERM = 1; // Max edits for terms < 4 chars
const FUZZY_MAX_EDITS_LONG_TERM_DIVISOR = 3; // For longer terms: length/3
const FUZZY_SHORT_TERM_THRESHOLD = 4; // Length threshold for "short" vs "long"

const MAX_RESULTS = 8;

// ============================================================================
// LEVENSHTEIN DISTANCE
// ============================================================================

/**
 * Minimum number of single-character edits to change a into b.
 * Used for fuzzy matching to handle typos and near-matches.
 */
function levenshteinDistance(a: string, b: string): number {
  const matrix: number[][] = [];

  for (let i = 0; i <= b.length; i++) {
    matrix[i] = [i];
  }
  for (let j = 0; j <= a.length; j++) {
    matrix[0][j] = j;
  }

  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b.charAt(i - 1) === a.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1, // substitution
          matrix[i][j - 1] + 1, // insertion
          matrix[i - 1][j] + 1, // deletion
        );
      }
    }
  }

  return matrix[b.length][a.length];
}

// ============================================================================
// SEARCH INDEX LOADING (same-origin only)
// ============================================================================

let searchIndex: unknown = null;
let searchIndexLoaded = false;

/**
 * Load the search index from the plugin's generated files.
 * The index only exists in production builds (not `docusaurus start`).
 */
async function loadSearchIndex(): Promise<any> {
  if (searchIndexLoaded && searchIndex) {
    return searchIndex;
  }

  try {
    const baseUrl = window.location.origin;
    const pathname = window.location.pathname;

    // Detect base path (e.g. /handbook/) — if the first segment is not a
    // known Docusaurus route, treat it as the basePath.
    let basePath = "";
    const pathSegments = pathname.split("/").filter(Boolean);
    if (pathSegments.length > 0) {
      const firstSegment = pathSegments[0];
      const knownRoutes = ["docs", "blog", "search"];
      if (!knownRoutes.includes(firstSegment)) {
        basePath = `/${firstSegment}`;
      }
    }

    // The plugin writes search-index.json at the build-output root.
    const possiblePaths = [
      `${baseUrl}${basePath}/search-index.json`,
      `${baseUrl}/search-index.json`,
    ];

    for (const path of possiblePaths) {
      try {
        const response = await fetch(path, {
          headers: { Accept: "application/json" },
        });
        if (response.ok) {
          const contentType = response.headers.get("content-type");
          if (contentType && contentType.includes("application/json")) {
            const data = await response.json();
            searchIndex = data;
            searchIndexLoaded = true;
            return data;
          }
        }
      } catch {
        continue;
      }
    }

    return null;
  } catch {
    // Silently fail — search is disabled without an index.
    return null;
  }
}

// ============================================================================
// LUNR QUERY BUILDING (bundled lunr, no CDN)
// ============================================================================

/**
 * Build Lunr query clauses combining exact, wildcard and fuzzy matching.
 * NOTE: the string syntax `term*~2` does NOT work in Lunr.js — the
 * programmatic query() API is required.
 */
function buildLunrQueryClauses(queryBuilder: any, term: string): void {
  const editDistance =
    term.length < FUZZY_SHORT_TERM_THRESHOLD
      ? FUZZY_MAX_EDITS_SHORT_TERM
      : Math.max(1, Math.floor(term.length / FUZZY_MAX_EDITS_LONG_TERM_DIVISOR));

  // 1. Exact match (highest precision)
  queryBuilder.term(term, {});

  // 2. Wildcard match for partial terms (e.g. "agen" matches "agent")
  queryBuilder.term(term, {
    wildcard: lunr.Query.wildcard.TRAILING,
    boost: 0.8,
  });

  // 3. Fuzzy match for typos (e.g. "agnt" matches "agent")
  queryBuilder.term(term, {
    editDistance,
    boost: 0.7,
  });

  // 4. Combined wildcard + fuzzy for maximum coverage
  queryBuilder.term(term, {
    wildcard: lunr.Query.wildcard.TRAILING,
    editDistance,
    boost: 0.5,
  });
}

// ============================================================================
// FALLBACK SEARCH WITH SCORING
// ============================================================================

/**
 * Additive 8-tier match score for one document against the search terms.
 * All terms must match at least one tier for the document to be included.
 */
function calculateDocumentScore(
  title: string,
  searchableText: string,
  searchTerms: string[],
): number {
  const titleLower = title.toLowerCase();
  const titleWords = titleLower.split(/\s+/);

  // PERFORMANCE: skip Levenshtein when exact matches already cover all terms.
  const exactMatchCounts = new Map<number, boolean>();
  for (let i = 0; i < searchTerms.length; i++) {
    exactMatchCounts.set(i, false);
  }

  let totalScore = 0;
  let allTermsMatched = true;

  for (let termIndex = 0; termIndex < searchTerms.length; termIndex++) {
    const term = searchTerms[termIndex];
    let termScore = 0;
    let termMatched = false;

    if (titleLower === term) {
      termScore += SCORE_WEIGHTS.EXACT_TITLE;
      termMatched = true;
      exactMatchCounts.set(termIndex, true);
    }

    if (titleLower.startsWith(term)) {
      termScore += SCORE_WEIGHTS.TITLE_STARTS_WITH;
      termMatched = true;
    }

    if (titleLower.includes(term)) {
      termScore += SCORE_WEIGHTS.SUBSTRING_IN_TITLE;
      termMatched = true;
    }

    if (titleWords.some((word) => word === term)) {
      termScore += SCORE_WEIGHTS.EXACT_WORD_IN_TITLE;
      termMatched = true;
    }

    if (
      titleWords.some((word) => word.startsWith(term) && word.length > term.length)
    ) {
      termScore += SCORE_WEIGHTS.PARTIAL_WORD_IN_TITLE;
      termMatched = true;
    }

    const hasExactMatches = Array.from(exactMatchCounts.values()).every(
      (v) => v,
    );
    if (!hasExactMatches) {
      const maxEdits = Math.max(
        FUZZY_MAX_EDITS_SHORT_TERM,
        Math.floor(term.length / FUZZY_MAX_EDITS_LONG_TERM_DIVISOR),
      );
      for (const word of titleWords) {
        const distance = levenshteinDistance(term, word);
        if (distance <= maxEdits) {
          termScore += Math.max(
            LEVENSHTEIN_MIN_SCORE,
            LEVENSHTEIN_BASE_SCORE - distance * LEVENSHTEIN_DISTANCE_PENALTY,
          );
          termMatched = true;
          break;
        }
      }
    }

    if (searchableText.includes(term)) {
      termScore += SCORE_WEIGHTS.IN_BREADCRUMBS;
      termMatched = true;
    }

    const wordsInText = searchableText.split(/\s+/);
    if (
      wordsInText.some(
        (word) => word.startsWith(term) && word.length >= term.length,
      )
    ) {
      termScore += SCORE_WEIGHTS.PARTIAL_IN_BREADCRUMBS;
      termMatched = true;
    }

    if (termMatched) {
      totalScore += termScore;
    } else {
      allTermsMatched = false;
      break;
    }
  }

  return allTermsMatched ? totalScore : 0;
}

// ============================================================================
// MAIN SEARCH FUNCTION
// ============================================================================

function parseBreadcrumbs(b: unknown): string[] {
  if (Array.isArray(b)) {
    return b;
  }
  if (typeof b === "string" && b.trim().startsWith("[")) {
    try {
      return JSON.parse(b);
    } catch {
      return [];
    }
  }
  return [];
}

/**
 * Search the loaded index: full-text via bundled Lunr when the index ships a
 * serialized lunr index, otherwise the additive title/breadcrumb fallback.
 *
 * found live (2026-08-13, fixture build, browser tier B13) — two upstream
 * bugs surfaced the first time this ran against a real
 * @easyops-cn/docusaurus-search-local index:
 *   1. The plugin writes an ARRAY of sub-indexes (titles, headings,
 *      descriptions, pages, content — each `{documents, index}`). Upstream
 *      searched only the FIRST element carrying documents, i.e. titles only,
 *      so a phrase that appears only in a doc's body returned nothing. Every
 *      sub-index is searched now and the results are merged; a section-level
 *      hit resolves its page title through its parent id (`p`).
 *   2. Lunr tokenizes on /[\s\-]+/, so a hyphenated query ("shorba-x7q1")
 *      passed as ONE term can never match the split tokens the index holds.
 *      Query terms are now split on lunr's own tokenizer separator.
 */
export async function searchContent(query: string): Promise<SearchResult[]> {
  if (!query.trim()) {
    return [];
  }

  const index = await loadSearchIndex();
  if (!index) {
    // Dev mode — index only exists in production builds. Empty, silently.
    return [];
  }

  const searchTerms = query
    .toLowerCase()
    .split(lunr.tokenizer.separator)
    .filter((term) => term.length > 0);

  // Normalize every known on-disk shape to a list of {documents, index?}.
  const subIndexes: any[] = Array.isArray(index)
    ? index
    : index.documents && Array.isArray(index.documents)
      ? [index]
      : index.docs && Array.isArray(index.docs)
        ? [{ documents: index.docs }]
        : [];

  // Page-level documents (no parent) by id — resolves the page title for
  // heading/content hits, whose own `t` is the matched text, not the title.
  const pagesById = new Map<string, any>();
  for (const sub of subIndexes) {
    for (const d of sub.documents ?? []) {
      if (d && d.p == null && d.i != null && !pagesById.has(String(d.i))) {
        pagesById.set(String(d.i), d);
      }
    }
  }

  const collected: { doc: any; score: number }[] = [];

  for (const sub of subIndexes) {
    const documents: any[] = Array.isArray(sub?.documents) ? sub.documents : [];
    if (documents.length === 0) {
      continue;
    }

    // Full-text search with the bundled lunr
    if (sub.index) {
      try {
        const idx = lunr.Index.load(sub.index);
        const searchResults = idx.query((queryBuilder: any) => {
          for (const term of searchTerms) {
            buildLunrQueryClauses(queryBuilder, term);
          }
        });
        for (const result of searchResults) {
          // result.ref is the document ID (string); match doc.i (also string)
          const docMatch = documents.find(
            (d: any) => String(d.i) === String(result.ref),
          );
          if (docMatch) {
            collected.push({ doc: docMatch, score: result.score || 0 });
          }
        }
        continue;
      } catch (error) {
        // Lunr search failed — fall through to the simple search.
        console.warn(
          "Lunr search failed, falling back to simple search:",
          error,
        );
      }
    }

    // Fallback: title/breadcrumb search with fuzzy matching
    for (const docItem of documents) {
      const title = docItem.t || docItem.title || "";
      const breadcrumbs = parseBreadcrumbs(docItem.b);
      const searchableText = [title, ...breadcrumbs]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();
      const score = calculateDocumentScore(title, searchableText, searchTerms);
      if (score > 0) {
        collected.push({ doc: docItem, score });
      }
    }
  }

  // Known niggle (recorded 2026-08-13, live walk): after this merge of all
  // sub-indexes, a section-level lunr hit can outscore the page's own
  // title-index hit, so searching an exact doc title may rank "Title › Section"
  // above the "Title" page itself. Cosmetic, not contract-bound (B13 requires
  // only that a result links to the doc); boosting exact-title matches is
  // optional polish if it ever grates.
  collected.sort((a, b) => b.score - a.score);

  const results: SearchResult[] = [];
  const seenUrls = new Set<string>();
  for (const { doc, score } of collected) {
    const baseUrl = doc.u || doc.url || doc.href || "";
    const url = `${baseUrl}${doc.h || ""}`;
    if (!url || seenUrls.has(url)) {
      continue;
    }
    seenUrls.add(url);

    const parent = doc.p != null ? pagesById.get(String(doc.p)) : undefined;
    const pageTitle: string = (parent && parent.t) || doc.s || doc.t || "";
    const breadcrumbs = parseBreadcrumbs(doc.b);
    const section =
      typeof doc.s === "string" && doc.s && doc.s !== pageTitle ? doc.s : "";

    results.push({
      title: pageTitle || url.split("/").pop() || "Untitled",
      url,
      text: breadcrumbs.length > 0 ? breadcrumbs.join(" > ") : section,
      type: "doc",
      score,
    });
    if (results.length >= MAX_RESULTS) {
      break;
    }
  }

  return results;
}

// Exported for tests
export { levenshteinDistance, calculateDocumentScore };
