import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The sidebar is the corpus's own folder tree, generated.
 *
 * Upstream replaced this with a `sidebarItemsGenerator` that hardcoded roughly
 * fifty document ids of one specific corpus into five named groups. A framework
 * cannot know a corpus's shape, so the shape comes from disk: folders become
 * categories, `_category_.json` names them, and a project that wants a
 * different arrangement writes it in its own `site/sidebars.ts`, which the
 * config prefers over this file when it exists.
 *
 * The name is `tutorialSidebar` on purpose and it is not cosmetic: it is the
 * name create-docusaurus gives every site, so a document copied in from an
 * existing Docusaurus project — carrying `displayed_sidebar: tutorialSidebar`
 * in its frontmatter — builds here without being edited first. It is also the
 * name a project's own `site/sidebars.ts` is scaffolded with, so the two files
 * are interchangeable and a `type: "docSidebar"` navbar item survives the swap.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
